### ISSUE TITLE
Addon tests issue

### ISSUE THREAD

**Issue by lifeart** [crashco/ember-template-component-import#3]
![image](https://user-images.githubusercontent.com/1360552/50922301-40029000-145b-11e9-8dab-93fe5dc225b8.png)

* windows

**Comment by davewasmer** [comment]
Hm, they are passing for me locally, and on CircleCI. Is this master?

**Comment by lifeart** [comment]
yes, master fork

**Comment by lifeart** [comment]
Gonna fix it in https://github.com/crashco/ember-template-component-import/pull/2
