### ISSUE TITLE
Extraneous whitespace in import statement

### ISSUE THREAD

**Issue by davewasmer** [crashco/ember-template-component-import#4]
If there is extra whitespace in the import statement, it appears that the regex pattern that looks for those statements misses it.

Need to update the regex to properly account for non-significant whitespace wherever it might occur in the import statement.

**Comment by lifeart** [comment]
looks like `\{\{\s*import\s*(\w+)\s*from\s*['"]([^'"]+)['"]\s*\}\}`
working 

https://regexr.com/

```
{{import Button from "ui/button"}}
{{import LocalButton from "./button"}}
{{import dirtyNamedGlobal from "ui/button"}}
{{import dirtyNamedLocal from "./button"}}
{{import  Button from "ui/button"}}
{{import LocalButton from "./button"}}
{{import dirtyNamedGlobal from "ui/button"}}
{{import 
dirtyNamedLocal
from
"./button"}}
{{ import   dirtyNamedLocal    from "./dds" }}
```
